# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_CMDID_MSGTYPE = descriptor.EnumDescriptor(
  name='msgType',
  full_name='CMSimulator.cmdID.msgType',
  filename='msgType',
  values=[
    descriptor.EnumValueDescriptor(
      name='CMD_NOCMD', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CMD_SIMULATOR_START', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CMD_SIMULATOR_STOP', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CMD_SIMULATOR_SHOWCMTS', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ANS_NOANSWER', index=4, number=50,
      options=None,
      type=None),
  ],
  options=None,
)


_CMDID = descriptor.Descriptor(
  name='cmdID',
  full_name='CMSimulator.cmdID',
  filename='simuProtocol.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _CMDID_MSGTYPE,
  ],
  options=None)


_CMDSIZE = descriptor.Descriptor(
  name='cmdSize',
  full_name='CMSimulator.cmdSize',
  filename='simuProtocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='CMSimulator.cmdSize.id', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='CMSimulator.cmdSize.size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_LISTCM = descriptor.Descriptor(
  name='listCM',
  full_name='CMSimulator.listCM',
  filename='simuProtocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cmMac', full_name='CMSimulator.listCM.cmMac', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cmtsMac', full_name='CMSimulator.listCM.cmtsMac', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg', full_name='CMSimulator.listCM.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ip', full_name='CMSimulator.listCM.ip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timer_dhcp_discover', full_name='CMSimulator.listCM.timer_dhcp_discover', index=4,
      number=5, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timer_dhcp_offer', full_name='CMSimulator.listCM.timer_dhcp_offer', index=5,
      number=6, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timer_dhcp_request', full_name='CMSimulator.listCM.timer_dhcp_request', index=6,
      number=7, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timer_dhcp_ack', full_name='CMSimulator.listCM.timer_dhcp_ack', index=7,
      number=8, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CLIENTCOMMAND_LISTCMTS = descriptor.Descriptor(
  name='listCMTS',
  full_name='CMSimulator.clientCommand.listCMTS',
  filename='simuProtocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cmtsMac', full_name='CMSimulator.clientCommand.listCMTS.cmtsMac', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cmtsIP', full_name='CMSimulator.clientCommand.listCMTS.cmtsIP', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cmtsName', full_name='CMSimulator.clientCommand.listCMTS.cmtsName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("CMTS_Unknown", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='helperAddressIP', full_name='CMSimulator.clientCommand.listCMTS.helperAddressIP', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='helperAddressMAC', full_name='CMSimulator.clientCommand.listCMTS.helperAddressMAC', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_CLIENTCOMMAND = descriptor.Descriptor(
  name='clientCommand',
  full_name='CMSimulator.clientCommand',
  filename='simuProtocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='CMSimulator.clientCommand.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='devices', full_name='CMSimulator.clientCommand.devices', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='CMTSDevices', full_name='CMSimulator.clientCommand.CMTSDevices', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SIMULATORANSWER = descriptor.Descriptor(
  name='simulatorAnswer',
  full_name='CMSimulator.simulatorAnswer',
  filename='simuProtocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='CMSimulator.simulatorAnswer.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='macCmts', full_name='CMSimulator.simulatorAnswer.macCmts', index=1,
      number=2, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='macCms', full_name='CMSimulator.simulatorAnswer.macCms', index=2,
      number=3, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ipCM', full_name='CMSimulator.simulatorAnswer.ipCM', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cablemodems', full_name='CMSimulator.simulatorAnswer.cablemodems', index=4,
      number=5, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CMDSIZE.fields_by_name['id'].enum_type = _CMDID_MSGTYPE
_CLIENTCOMMAND.fields_by_name['devices'].message_type = _LISTCM
_CLIENTCOMMAND.fields_by_name['CMTSDevices'].message_type = _CLIENTCOMMAND_LISTCMTS
_SIMULATORANSWER.fields_by_name['cablemodems'].message_type = _LISTCM

class cmdID(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMDID

class cmdSize(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CMDSIZE

class listCM(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LISTCM

class clientCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class listCMTS(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CLIENTCOMMAND_LISTCMTS
  DESCRIPTOR = _CLIENTCOMMAND

class simulatorAnswer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIMULATORANSWER

